### PR TITLE
Update sounds for HotA

### PR DESCRIPTION
**Pull request by krs0**
Remaining unused sounds:
CAMPAIGN sounds (HORN_X, ROGER_X, TERROR_X)
HORSE11 - Airship?
LOOPMFOR - ?
LOOPELAL - Altar of thought?

### CODE REVIEW

**Comment by GeorgeK1ng** [comment]
Please reflect in hota/Mods/heroes3DataPatch/mod.json changes from https://github.com/vcmi-mods/horn-of-the-abyss/pull/162

**Comment by misiokles** [comment]
Ben Yan asked for not updating Factory folder till official Factory premiere with vcmi-1.6.

**Comment by krs0** [comment]
Ok. Then discard this PR.

**Comment by misiokles** [comment]
No, we will wait few weeks. Or just remove Factory content. Rest will be merged.

**Comment by krs0** [comment]
I do not see a reason that we need to wait for weeks  to merge these fixes.

Just merge them in if changes are ok, and another modder can use latest repo like everybody else.

**Comment by Olegmods** [comment]
> I do not see a reason that we need to wait for weeks to merge these fixes.
> 
> Just merge them in if changes are ok, and another modder can use latest repo like everybody else.

Well, you've added the 2nd sound of Gold Golem's death as the main one, I guess there is no reason to change Gold Golem's sounds rn, since the sounds from the ranged death aren't supported in VCMI AFAIK.

**Comment by krs0** [comment]
Thanks for reviewing! I thought that DETH file replaces somehow normal KILL version.
Will revert that change from this PR.

**Comment by krs0** [comment]
Closing this one. Will make the change in a separate branch.

**Pull request closed without merging**
