### PR TITLE
avoid overriding hd mod data

### PR DESCRIPTION
**Pull request by Laserlicht**
@misiokles

### CODE REVIEW

**Comment by Olegmods** [comment]
@Laserlicht maybe it'll be better if the HD mod will soft depend on HotA?

**Comment by Laserlicht** [comment]
> @Laserlicht maybe it'll be better if the HD mod will soft depend on HotA?

Also possible. But prefer it that way. With `softDepend` it's invisible what happens in background. With `conflicts` it's clearly visible in launcher.

**Comment by Olegmods** [comment]
> > @Laserlicht maybe it'll be better if the HD mod will soft depend on HotA?
> 
> Also possible. But prefer it that way. With `softDepend` it's invisible what happens in background. With `conflicts` it's clearly visible in launcher.

Well, a lot of people (myself included) will prefer HD mod to be compatible with HotA, to be fair.

**Comment by misiokles** [comment]
From what I see, it's still compatibke with hota, only two graphical submods are excluded.

**Comment by Laserlicht** [comment]
Yes. Only two submods with new graphics are marked as conflict (they will override hd graphics).

Basically it's playable without problems. Only thing is missing these new graphics.

**Comment by Olegmods** [comment]
> From what I see, it's still compatible with hota, only two graphical submods are excluded.

>Basically it's playable without problems. Only thing is missing these new graphics.

The thing is that HotA adds some more things than HD Edition mod, for example, some portraits not present in HD were fixed.
But current implementation is sort of okay, but I suspect 'softDepends' in HD mod will be better.

**Comment by Laserlicht** [comment]
> The thing is that HotA adds some more things than HD Edition mod, for example, some portraits not present in HD were fixed. But current implementation is sort of okay, but I suspect 'softDepends' in HD mod will be better.

Yes. But then we need full hd support here in HotA. :)

I think more people will asking: "Why is my game not in HD even if I installed the mod?" than "Why are some portraits looks minimal different than in HotA?"

And changing HD mod isn't that easy because there is no update process.

**Comment by Olegmods** [comment]
> Yes. But then we need full hd support here in HotA. :)

Seriously, that's a good idea, but it needs a lot of work with upscaling stuff and doing things in HDE (HD Edition) style, so it's not easy obviously.

> I think more people will asking: "Why is my game not in HD even if I installed the mod?" than "Why are some portraits looks minimal different than in HotA?"

I meant the portraits that aren't HD even with HDE mod, like Trolls. If there will be soft dependency in HDE mod, Trolls will have their HotA portrait (not SoD one) and Pikeman will use HD portrait. But the only problem is Elementals' portraits, which are neutral in RoE (and HDE).

> And changing HD mod isn't that easy because there is no update process.

If that's the problem, then sure.

**Pull request merged**
