### PR TITLE
Seafaring Academy changes

### PR DESCRIPTION
**Pull request by krs0**
Limit is now 3 skills instead of 4 (like in HotA)
Reorganized json
image

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Can somebody post a screenshot of this building from hota? It definitely should not like this.

@krs0 can you bump hota mod version, either here or in Junkman PR? So players will get update notification.

And we should probably limit any reorganization of mod structure / layout to avoid save breakage on 1.3. Can create 1.4 branch for such PR's

**Comment by krs0** [comment]
Yes you are right. Upgrade is possible in HotA.
Having an empty slot is not a biggie... but not being able to upgrade is meh...

1st visit
image
3rd visit
image

**Comment by krs0** [comment]
@IvanSavenko Tested in HotA:

Basically the building has 3 skills to offer. For each visiting hero looks to current hero skills and based on what is he missing he will get the next skill level.

- So no need to track anything on a per hero basis (just read the current skills the hero has and offer the according levels)

- A hero can visit as many times as he wants.

- A hero can update as many skills from the 3 as he wants.

**Comment by IvanSavenko** [comment]
Thanks for research. Will update hota project with this info

**Pull request merged**
