### PR TITLE
Add the Jebus Outcast to the mod

### PR DESCRIPTION
**Pull request by Olegmods**

### CODE REVIEW

**Comment by krs0** [comment]
I still have these errors.

image

**Comment by Olegmods** [comment]
> I still have these errors.
> 
> image

#166

**Comment by misiokles** [comment]
Because link to templates should start with "config" - "config/hota nostalgia.json"

**Comment by Olegmods** [comment]
> Because link to templates should start with "config" - "config/hota nostalgia.json"

I fixed that in #166 .

**Pull request merged**
